django-postgres/postgresTest/cars/urls.py
from django.urls import path

from . import views



urlpatterns = [

    # path("<int:pk>/", views.car_detail, name="car_detail"),
    # path("add/", views.add, name="add"),

    

]

django-postgres/postgresTest/drivers/urls.py
from django.urls import path

from . import views



urlpatterns = [

    path("", views.alldriver, name="alldrivers"),

    path("<int:pk>/", views.driver_detail, name="driver_detail"),

    

]

django-postgres/postgresTest/postgresTest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from rest_framework import routers
from cars import views

# router = routers.DefaultRouter()
# router.register(r'cars', views.CarView, 'cars')

urlpatterns = [

    path('admin/', admin.site.urls),

    path("cars/", include("cars.urls")),

    path("drivers/", include("drivers.urls")),
    
    path('api/', views.car_list),

    path('api/<int:pk>', views.car_detail),

    path('api/driver', views.driver_list),

    path('api/driver/<int:pk>', views.driver_detail),

    

]

django-postgres/postgresTest/cars/models.py
from django.db import models

# Create your models here.
class Driver(models.Model):
    
    name = models.TextField()

    license = models.TextField()
    
    car = models.ForeignKey("Car", on_delete=models.SET_NULL, null=True,related_name='owner')

    def __str__(self):
        return self.name


class Car(models.Model):

    make = models.TextField()

    model = models.TextField()

    year = models.IntegerField()

    img = models.TextField(null=True)

    vin = models.TextField()

    def __str__(self):
        return self.model

   

    

django-postgres/postgresTest/drivers/models.py
from django.db import models

# Create your models here.

django-postgres/postgresTest/testdb/models.py
from django.db import models
# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=80)
    age = models.IntegerField()

django-postgres/postgresTest/cars/views.py
from lib2to3.pgen2 import driver
from statistics import mode
from typing import OrderedDict
from django.shortcuts import render
from rest_framework.decorators import api_view
# Create your views here.
from cars.models import Car, Driver
from rest_framework import viewsets
from .serializers import CarSerializer
from .models import Car
from rest_framework.response import Response
from django.shortcuts import get_object_or_404, render
from rest_framework import status
from .serializers import DriverSerializer

# Create your views here.

@api_view(['GET', 'POST'])
def car_list(request ,format=None):
    """
    """
    if request.method == 'GET':
        cars = Car.objects.order_by('id')
        serializer = CarSerializer(cars, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = CarSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def car_detail(request, pk):

    try:
        car = Car.objects.get(pk=pk)
    except Car.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CarSerializer(car)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = CarSerializer(Car, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        car.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
def driver_list(request , format=None):
    """
    """
    if request.method == 'GET':
        driver = Driver.objects.order_by('id')
        serializer = DriverSerializer(driver, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = CarSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['GET', 'PUT', 'DELETE'])
def driver_detail(request, pk):

    try:
        driver = Driver.objects.get(pk=pk)
    except Driver.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = DriverSerializer(driver)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = DriverSerializer(Driver, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        driver.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)






def car_detail1(request, pk):

    

    owner_obj = Driver.objects.get(pk=pk)

    car_objs = Car.objects.filter(owner_id=owner_obj.id)

    context = {

        "vehicles": car_objs,

        "drivers": owner_obj,

    }


    return render(request, "car_detail.html", context)

django-postgres/postgresTest/drivers/views.py
from django.shortcuts import render
from matplotlib.style import context

# Create your views here.

from cars.models import  Driver

def driver_detail(request, pk):
    
    

    owner_obj = Driver.objects.get(pk=pk)


    context = {

        "drivers": owner_obj,

    }


    return render(request, "driver_detail.html", context)


def alldriver(request):
    

    owner_obj = Driver.objects.all()


    context={

        'alldrivers' : owner_obj

    }

    return render(request,"alldrivers.html",context)

django-postgres/postgresTest/testdb/views.py
from django.shortcuts import render

# Create your views here.

django-postgres/postgresTest/cars/templates/base.html
<!doctype html>

<html>

    <head>

        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">



        <title>Contacts</title>

        <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>

    </head>

    <body>

{% block page_content %}{% endblock %}

    </body>

</html>

django-postgres/postgresTest/cars/templates/car_detail.html
{% extends "base.html" %}

{% block page_content %}

        <div class="mw6 center pa3 sans-serif">

            <h1 class="mb4">Driver: {{ drivers.name | linebreaks }}</h1>

            <header class="b mb2">License: {{ drivers.license }}</header>

        {% for v in vehicles %}

            <div class="pa2 mb3 striped--near-white">

                <div class="pl2">

                    <p class="mb2">Make/Model: {{ v.make }} {{ v.model }}</p>

                    <p class="mb2">Year: {{ v.year }}</p>

                    <p class="mb2">Vin: {{ v.vin }}</p>

                </div>

            </div>

        {% endfor %}

        </div>

{% endblock %}

django-postgres/postgresTest/drivers/templates/alldrivers.html
{% extends "base.html" %}

{% block page_content %}
    {% for d in alldrivers %}

        <div class="mainalldrivers mw6 center pa3 sans-serif">

            <h1 class="mb4">Driver {{d.id}}: {{ d.name | linebreaks }}</h1>

            <header class="b mb2">License: {{ d.license }}</header>

            {% for c in d.car_set.all %}
            <h3>car model :{{c.model}}</h3>
            {% endfor %}
            
        </div>
    {% endfor %}


{% endblock %}

django-postgres/postgresTest/drivers/templates/base.html
<!doctype html>

<html>

    <head>

        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'drivers/style.css' %}">

        <title>Contacts</title>

        <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>

    </head>

    <body>

{% block page_content %}{% endblock %}

    </body>

</html>

django-postgres/postgresTest/drivers/templates/driver_detail.html
{% extends "base.html" %}

{% block page_content %}

        <div class="mw6 center pa3 sans-serif">

            <h1 class="mb4">Driver: {{ drivers.name | linebreaks }}</h1>

            <header class="b mb2">License: {{ drivers.license }}</header>
            
        </div>

{% endblock %}